# Generated by Django 6.0.4 on 2026-04-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_due_date'),
    ]

    operations = [
    ]
