# Generated by Django 6.0.4 on 2026-04-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260409_2111'),
    ]

    operations = [
    ]
